# Hidden Markov Model for Named Entity Recognition

In [1]:
import pandas as pd
import collections
import math
from sklearn.metrics import classification_report

In [2]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet'}

df_train = pd.read_parquet("hf://datasets/lhoestq/conll2003/" + splits["train"])
df_test = pd.read_parquet("hf://datasets/lhoestq/conll2003/" + splits["test"])

C:\Users\BluRay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df_train.head()

,id,tokens,pos_tags,chunk_tags,ner_tags
0,0,"[EU, rejects, German, call, to, boycott, Briti...","[22, 42, 16, 21, 35, 37, 16, 21, 7]","[11, 21, 11, 12, 21, 22, 11, 12, 0]","[3, 0, 7, 0, 0, 0, 7, 0, 0]"
1,1,"[Peter, Blackburn]","[22, 22]","[11, 12]","[1, 2]"
2,2,"[BRUSSELS, 1996-08-22]","[22, 11]","[11, 12]","[5, 0]"
3,3,"[The, European, Commission, said, on, Thursday...","[12, 22, 22, 38, 15, 22, 28, 38, 15, 16, 21, 3...","[11, 12, 12, 21, 13, 11, 11, 21, 13, 11, 12, 1...","[0, 3, 4, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, ..."
4,4,"[Germany, 's, representative, to, the, Europea...","[22, 27, 21, 35, 12, 22, 22, 27, 16, 21, 22, 2...","[11, 11, 12, 13, 11, 12, 12, 11, 12, 12, 12, 1...","[5, 0, 0, 0, 0, 3, 4, 0, 0, 0, 1, 2, 0, 0, 0, ..."

Since we only need NER tags, we can ignore POS and chunk tags.

In [4]:
df_train.drop(columns=["chunk_tags", "pos_tags"], inplace=True)
df_test.drop(columns=["chunk_tags", "pos_tags"], inplace=True)

df_train.head()

,id,tokens,ner_tags
0,0,"[EU, rejects, German, call, to, boycott, Briti...","[3, 0, 7, 0, 0, 0, 7, 0, 0]"
1,1,"[Peter, Blackburn]","[1, 2]"
2,2,"[BRUSSELS, 1996-08-22]","[5, 0]"
3,3,"[The, European, Commission, said, on, Thursday...","[0, 3, 4, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, ..."
4,4,"[Germany, 's, representative, to, the, Europea...","[5, 0, 0, 0, 0, 3, 4, 0, 0, 0, 1, 2, 0, 0, 0, ..."

#### NER Tags

0: "O" (Outside of a named entity)

1: "B-PER" (Beginning of a person's name)

2: "I-PER" (Inside of a person's name)

3: "B-ORG" (Beginning of an organization)

4: "I-ORG" (Inside of an organization)

5: "B-LOC" (Beginning of a location)

6: "I-LOC" (Inside of a location)

7: "B-MISC" (Beginning of a miscellaneous entity)

8: "I-MISC" (Inside of a miscellaneous entity)

## Model Training

### Counting Tags and Transitions

In [5]:
tag_counts = collections.defaultdict(int)
transition_counts = collections.defaultdict(int)
emission_counts = collections.defaultdict(int)

# each row represents a sentence, which contain tonkens and NER tags
for _, row in df_train.iterrows():
    tokens = row['tokens']
    tags = row['ner_tags']
    
    # starting tag
    prev_tag = "<START>"
    tag_counts[prev_tag] += 1
    
    # iterate through the words and tags at the same time
    for word, tag in zip(tokens, tags):
        # increment counts
        tag_counts[tag] += 1
        transition_counts[(prev_tag, tag)] += 1
        emission_counts[(tag, word)] += 1
        
        # use current tag for next iteration
        prev_tag = tag

### Calculating Probabilities Using Counts

In [6]:
transition_probs = {}
for (prev_tag, tag), count in transition_counts.items():
    transition_probs[(prev_tag, tag)] = count / tag_counts[prev_tag]

emission_probs = {}
for (tag, word), count in emission_counts.items():
    emission_probs[(tag, word)] = count / tag_counts[tag]

In [7]:
for transition in list(transition_probs.items()):
    print(transition)

(('<START>', np.int64(3)), 0.17484509650309807)
((np.int64(3), np.int64(0)), 0.586141433317513)
((np.int64(0), np.int64(7)), 0.016871292266685538)
((np.int64(7), np.int64(0)), 0.705933682373473)
((np.int64(0), np.int64(0)), 0.8190095413320124)
(('<START>', np.int64(1)), 0.09607577807848444)
((np.int64(1), np.int64(2)), 0.649090909090909)
(('<START>', np.int64(5)), 0.11259881774802365)
((np.int64(5), np.int64(0)), 0.8323529411764706)
(('<START>', np.int64(0)), 0.5807278683854427)
((np.int64(0), np.int64(3)), 0.022361391218200473)
((np.int64(3), np.int64(4)), 0.39313399778516056)
((np.int64(4), np.int64(0)), 0.6479481641468683)
((np.int64(0), np.int64(1)), 0.030564106193020323)
((np.int64(2), np.int64(0)), 0.9070229681978799)
((np.int64(0), np.int64(5)), 0.03262805316727406)
((np.int64(2), np.int64(2)), 0.053886925795053005)
((np.int64(1), np.int64(0)), 0.34045454545454545)
((np.int64(7), np.int64(8)), 0.24956369982547993)
((np.int64(8), np.int64(8)), 0.2571428571428571)
((np.int64(8), np.int64(0)), 0.6277056277056277)
(('<START>', np.int64(7)), 0.03575243928495121)
((np.int64(4), np.int64(4)), 0.3291036717062635)
((np.int64(5), np.int64(6)), 0.1457983193277311)
((np.int64(6), np.int64(0)), 0.8504753673293)
((np.int64(6), np.int64(5)), 0.0025929127052722557)
((np.int64(7), np.int64(3)), 0.009307737056428156)
((np.int64(7), np.int64(5)), 0.002326934264107039)
((np.int64(6), np.int64(6)), 0.10025929127052723)
((np.int64(7), np.int64(7)), 0.009016870273414777)
((np.int64(3), np.int64(7)), 0.0009492168960607499)
((np.int64(1), np.int64(7)), 0.00015151515151515152)
((np.int64(7), np.int64(1)), 0.01687027341477603)
((np.int64(8), np.int64(1)), 0.0025974025974025974)
((np.int64(5), np.int64(3)), 0.0014005602240896359)
((np.int64(8), np.int64(3)), 0.006060606060606061)
((np.int64(5), np.int64(7)), 0.003781512605042017)
((np.int64(6), np.int64(7)), 0.0025929127052722557)
((np.int64(3), np.int64(1)), 0.00047460844803037496)
((np.int64(4), np.int64(1)), 0.0008099352051835853)
((np.int64(1), np.int64(5)), 0.00045454545454545455)
((np.int64(8), np.int64(7)), 0.003463203463203463)
((np.int64(5), np.int64(1)), 0.00014005602240896358)
((np.int64(4), np.int64(7)), 0.0008099352051835853)
((np.int64(4), np.int64(5)), 0.0002699784017278618)
((np.int64(5), np.int64(5)), 0.0011204481792717086)
((np.int64(4), np.int64(3)), 0.0016198704103671706)
((np.int64(3), np.int64(3)), 0.0028476506881822496)
((np.int64(3), np.int64(5)), 0.00015820281601012498)
((np.int64(8), np.int64(5)), 0.0017316017316017316)
((np.int64(6), np.int64(3)), 0.000864304235090752)

In [8]:
print("\nEmissions:")
for emission in list(emission_probs.items()):
    print(emission)

Emissions:
((np.int64(3), 'EU'), 0.0037968675842429997)
((np.int64(0), 'rejects'), 5.896991355010673e-06)
((np.int64(7), 'German'), 0.02443280977312391)
((np.int64(0), 'call'), 0.0001769097406503202)
((np.int64(0), 'to'), 0.0199436247626461)
((np.int64(0), 'boycott'), 2.9484956775053368e-05)
((np.int64(7), 'British'), 0.02268760907504363)
((np.int64(0), 'lamb'), 1.769097406503202e-05)
((np.int64(0), '.'), 0.04341365035558858)
((np.int64(1), 'Peter'), 0.004696969696969697)
((np.int64(2), 'Blackburn'), 0.00022084805653710247)
((np.int64(5), 'BRUSSELS'), 0.002240896358543417)
((np.int64(0), '1996-08-22'), 0.0007371239193763342)
((np.int64(0), 'The'), 0.006445411551026666)
((np.int64(3), 'European'), 0.004587881664293625)
((np.int64(4), 'Commission'), 0.0091792656587473)
((np.int64(0), 'said'), 0.010885846041349703)
((np.int64(0), 'on'), 0.012006274398801732)
((np.int64(0), 'Thursday'), 0.001680642536178042)
((np.int64(0), 'it'), 0.0032610362193209023)
((np.int64(0), 'disagreed'), 1.1793982710021346e-05)
((np.int64(0), 'with'), 0.004953472738208966)
((np.int64(0), 'advice'), 2.9484956775053368e-05)
((np.int64(0), 'consumers'), 5.307292219509606e-05)
((np.int64(0), 'shun'), 5.896991355010673e-06)
((np.int64(0), 'until'), 0.0003125405418155657)
((np.int64(0), 'scientists'), 3.538194813006404e-05)
((np.int64(0), 'determine'), 6.48669049051174e-05)
((np.int64(0), 'whether'), 0.0002653646109754803)
((np.int64(0), 'mad'), 7.666088761513875e-05)
((np.int64(0), 'cow'), 7.076389626012808e-05)
((np.int64(0), 'disease'), 0.00020639469742537357)
((np.int64(0), 'can'), 0.00041868638620575784)
((np.int64(0), 'be'), 0.0030959204613806037)
((np.int64(0), 'transmitted'), 1.1793982710021346e-05)
((np.int64(0), 'sheep'), 7.076389626012808e-05)
((np.int64(5), 'Germany'), 0.019747899159663865)
((np.int64(0), "'s"), 0.008821899067095967)
((np.int64(0), 'representative'), 4.127893948507472e-05)
((np.int64(0), 'the'), 0.042582174574532075)
((np.int64(4), 'Union'), 0.010529157667386609)
((np.int64(0), 'veterinary'), 4.7175930840085385e-05)
((np.int64(0), 'committee'), 0.0001297338098102348)
((np.int64(1), 'Werner'), 0.00030303030303030303)
((np.int64(2), 'Zwingmann'), 0.00044169611307420494)
((np.int64(0), 'Wednesday'), 0.0015037327955277219)
((np.int64(0), 'should'), 0.00045996532569083254)
((np.int64(0), 'buy'), 0.0001533217752302775)
((np.int64(0), 'sheepmeat'), 1.1793982710021346e-05)
((np.int64(0), 'from'), 0.00446402245574308)
((np.int64(0), 'countries'), 0.0002476736369104483)
((np.int64(0), 'other'), 0.0007784028588614089)
((np.int64(0), 'than'), 0.000849166755121537)
((np.int64(5), 'Britain'), 0.018627450980392157)
((np.int64(0), 'scientific'), 5.307292219509606e-05)
((np.int64(0), 'was'), 0.006457205533736687)
((np.int64(0), 'clearer'), 5.896991355010673e-06)
((np.int64(0), '"'), 0.012843647171213246)
((np.int64(0), 'We'), 0.0008078878156364623)
((np.int64(0), 'do'), 0.0006250810836311314)
((np.int64(0), "n't"), 0.0005720081614360354)
((np.int64(0), 'support'), 0.0003597164726556511)
((np.int64(0), 'any'), 0.000542523204660982)
((np.int64(0), 'such'), 0.00023587965420042694)
((np.int64(0), 'recommendation'), 1.769097406503202e-05)
((np.int64(0), 'because'), 0.0006722570144712168)
((np.int64(0), 'we'), 0.0009612095908667397)
((np.int64(0), 'see'), 0.00016511575794029887)
((np.int64(0), 'grounds'), 3.538194813006404e-05)
((np.int64(0), 'for'), 0.008291169845145007)
((np.int64(0), ','), 0.04290061210770265)
((np.int64(3), 'Commission'), 0.0017402309761113748)
((np.int64(0), 'chief'), 0.0002948495677505337)
((np.int64(0), 'spokesman'), 0.0006250810836311314)
((np.int64(1), 'Nikolaus'), 0.00015151515151515152)
((np.int64(2), 'van'), 0.0035335689045936395)
((np.int64(2), 'der'), 0.001987632508833922)
((np.int64(2), 'Pas'), 0.00022084805653710247)
((np.int64(0), 'told'), 0.001173501279647124)
((np.int64(0), 'a'), 0.017655592116901958)
((np.int64(0), 'news'), 0.0005012442651759072)
((np.int64(0), 'briefing'), 3.538194813006404e-05)
((np.int64(0), 'He'), 0.0012324711931972307)
((np.int64(0), 'further'), 0.00018870372336034154)
((np.int64(0), 'study'), 5.8969913550106735e-05)
((np.int64(0), 'required'), 4.7175930840085385e-05)
((np.int64(0), 'and'), 0.016446708889124768)
((np.int64(0), 'if'), 0.000577905152791046)
((np.int64(0), 'found'), 0.00036561346401066175)
((np.int64(0), 'that'), 0.004522992369293186)
((np.int64(0), 'action'), 0.00017101274929530954)
((np.int64(0), 'needed'), 0.00014152779252025617)
((np.int64(0), 'taken'), 0.0002417766455554376)
((np.int64(0), 'by'), 0.004222245810187642)
((np.int64(0), 'proposal'), 5.8969913550106735e-05)
((np.int64(0), 'last'), 0.00166295156211301)
((np.int64(0), 'month'), 0.0005248322305959499)
((np.int64(0), 'Farm'), 1.769097406503202e-05)
((np.int64(0), 'Commissioner'), 4.127893948507472e-05)
((np.int64(1), 'Franz'), 0.0006060606060606061)
((np.int64(2), 'Fischler'), 0.00044169611307420494)
((np.int64(0), 'ban'), 0.00021229168878038424)
((np.int64(0), 'brains'), 1.1793982710021346e-05)
((np.int64(0), 'spleens'), 1.1793982710021346e-05)
((np.int64(0), 'spinal'), 2.9484956775053368e-05)
((np.int64(0), 'cords'), 1.1793982710021346e-05)
((np.int64(0), 'human'), 0.00017101274929530954)
((np.int64(0), 'animal'), 4.7175930840085385e-05)
((np.int64(0), 'food'), 0.00012383681845522414)
((np.int64(0), 'chains'), 3.538194813006404e-05)
((np.int64(0), 'highly'), 3.538194813006404e-05)
((np.int64(0), 'specific'), 4.127893948507472e-05)
((np.int64(0), 'precautionary'), 5.896991355010673e-06)
((np.int64(0), 'move'), 0.00010614584439019212)
((np.int64(0), 'protect'), 2.3587965420042693e-05)
((np.int64(0), 'health'), 0.00014742478387526684)
((np.int64(1), 'Fischler'), 0.0006060606060606061)
((np.int64(0), 'proposed'), 8.84548703251601e-05)
((np.int64(7), 'EU-wide'), 0.00029086678301337986)
((np.int64(0), 'measures'), 9.435186168017077e-05)
((np.int64(0), 'after'), 0.0027774829282100275)
((np.int64(0), 'reports'), 0.00018870372336034154)
((np.int64(5), 'France'), 0.017086834733893556)
((np.int64(0), 'under'), 0.0009376216254466971)
((np.int64(0), 'laboratory'), 1.769097406503202e-05)
((np.int64(0), 'conditions'), 0.00014742478387526684)
((np.int64(0), 'could'), 0.0008432697637665263)
((np.int64(0), 'contract'), 0.00017101274929530954)
((np.int64(7), 'Bovine'), 0.0005817335660267597)
((np.int64(8), 'Spongiform'), 0.0017316017316017316)
((np.int64(8), 'Encephalopathy'), 0.0017316017316017316)
((np.int64(0), '('), 0.016782837396360377)
((np.int64(7), 'BSE'), 0.0031995346131471784)
((np.int64(0), ')'), 0.016782837396360377)
((np.int64(0), '--'), 0.0020993289223837997)
((np.int64(0), 'But'), 0.0009140336600266544)
((np.int64(0), 'agreed'), 0.0003125405418155657)
((np.int64(0), 'review'), 4.127893948507472e-05)
((np.int64(0), 'his'), 0.0031725813489957423)
((np.int64(0), 'standing'), 5.307292219509606e-05)
((np.int64(0), 'mational'), 5.896991355010673e-06)
((np.int64(0), 'officials'), 0.0007312269280213235)
((np.int64(0), 'questioned'), 7.076389626012808e-05)
((np.int64(0), 'justified'), 2.3587965420042693e-05)
((np.int64(0), 'as'), 0.0035499887957164255)
((np.int64(0), 'there'), 0.0007194329453113022)
((np.int64(0), 'only'), 0.0007371239193763342)
((np.int64(0), 'slight'), 3.538194813006404e-05)
((np.int64(0), 'risk'), 0.0001120428357452028)
((np.int64(7), 'Spanish'), 0.0037812681791739382)
((np.int64(0), 'Minister'), 0.0007135359539562915)
((np.int64(1), 'Loyola'), 0.00015151515151515152)
((np.int64(2), 'de'), 0.004858657243816254)
((np.int64(2), 'Palacio'), 0.00022084805653710247)
((np.int64(0), 'had'), 0.003308212150160988)
((np.int64(0), 'earlier'), 0.0004894502824658859)
((np.int64(0), 'accused'), 0.0002240856714904056)
((np.int64(0), 'at'), 0.005484201960159927)
((np.int64(0), 'an'), 0.0029897746169904116)
((np.int64(0), 'farm'), 0.00010024885303518145)
((np.int64(0), 'ministers'), 8.255787897014943e-05)
((np.int64(0), "'"), 0.0007725058675063983)
((np.int64(0), 'meeting'), 0.0005071412565309179)
((np.int64(0), 'of'), 0.021329417731073608)
((np.int64(0), 'causing'), 2.3587965420042693e-05)
((np.int64(0), 'unjustified'), 5.896991355010673e-06)
((np.int64(0), 'alarm'), 1.769097406503202e-05)
((np.int64(0), 'through'), 0.0006191840922761207)
((np.int64(0), 'dangerous'), 7.666088761513875e-05)
((np.int64(0), 'generalisation'), 5.896991355010673e-06)
((np.int64(0), 'Only'), 2.9484956775053368e-05)
((np.int64(0), 'backed'), 4.127893948507472e-05)
((np.int64(0), 'multidisciplinary'), 5.896991355010673e-06)
((np.int64(0), 'committees'), 1.1793982710021346e-05)
((np.int64(0), 'are'), 0.002040359008833693)
((np.int64(0), 'due'), 0.0004363773602707898)
((np.int64(0), 're-examine'), 1.1793982710021346e-05)
((np.int64(0), 'issue'), 0.00033023151588059774)
((np.int64(0), 'early'), 0.0004422743516258005)
((np.int64(0), 'next'), 0.0006486690490511741)
((np.int64(0), 'make'), 0.0003361285072356084)
((np.int64(0), 'recommendations'), 1.1793982710021346e-05)
((np.int64(0), 'senior'), 0.0001533217752302775)
((np.int64(0), 'Sheep'), 1.1793982710021346e-05)
((np.int64(0), 'have'), 0.0029543926688603474)
((np.int64(0), 'long'), 0.00020639469742537357)
((np.int64(0), 'been'), 0.002170092818643928)
((np.int64(0), 'known'), 0.00018280673200533087)
((np.int64(0), 'scrapie'), 1.1793982710021346e-05)
((np.int64(0), 'brain-wasting'), 1.769097406503202e-05)
((np.int64(0), 'similar'), 0.0001356308011652455)
((np.int64(0), 'which'), 0.0019460071471535223)
((np.int64(0), 'is'), 0.004063027043602354)
((np.int64(0), 'believed'), 0.00016511575794029887)
((np.int64(0), 'transferred'), 1.769097406503202e-05)
((np.int64(0), 'cattle'), 7.076389626012808e-05)
((np.int64(0), 'feed'), 0.00010614584439019212)
((np.int64(0), 'containing'), 2.9484956775053368e-05)
((np.int64(0), 'waste'), 4.127893948507472e-05)
((np.int64(0), 'farmers'), 0.0001120428357452028)
((np.int64(0), 'denied'), 0.00014152779252025617)
((np.int64(0), 'danger'), 5.8969913550106735e-05)
((np.int64(0), 'their'), 0.002040359008833693)
((np.int64(0), 'but'), 0.002293929637099152)
((np.int64(0), 'expressed'), 6.48669049051174e-05)
((np.int64(0), 'concern'), 0.00010024885303518145)
((np.int64(0), 'government'), 0.0015214237695927537)
((np.int64(0), 'avoid'), 8.84548703251601e-05)
((np.int64(0), 'might'), 0.00021229168878038424)
((np.int64(0), 'influence'), 2.3587965420042693e-05)
((np.int64(0), 'across'), 0.0002004977060703629)
((np.int64(5), 'Europe'), 0.004201680672268907)
((np.int64(0), 'What'), 7.076389626012808e-05)
((np.int64(0), 'extremely'), 4.7175930840085385e-05)
((np.int64(0), 'careful'), 5.896991355010673e-06)
((np.int64(0), 'how'), 0.00016511575794029887)
((np.int64(0), 'going'), 0.000306643550460555)
((np.int64(0), 'take'), 0.0004717593084008539)
((np.int64(0), 'lead'), 0.0004422743516258005)
((np.int64(3), 'Welsh'), 0.00015820281601012498)
((np.int64(4), 'National'), 0.004319654427645789)
((np.int64(4), 'Farmers'), 0.0005399568034557236)
((np.int64(4), "'"), 0.0008099352051835853)
((np.int64(3), 'NFU'), 0.00015820281601012498)
((np.int64(0), 'chairman'), 0.00015921876658528817)
((np.int64(1), 'John'), 0.007424242424242424)
((np.int64(2), 'Lloyd'), 0.0011042402826855124)
((np.int64(2), 'Jones'), 0.00265017667844523)
((np.int64(3), 'BBC'), 0.00031640563202024995)
((np.int64(4), 'radio'), 0.0005399568034557236)
((np.int64(5), 'Bonn'), 0.0011204481792717086)
((np.int64(0), 'has'), 0.003284624184740945)
((np.int64(0), 'led'), 0.0002181886801353949)
((np.int64(0), 'efforts'), 8.84548703251601e-05)
((np.int64(0), 'public'), 0.00019460071471535224)
((np.int64(0), 'consumer'), 8.84548703251601e-05)
((np.int64(0), 'confidence'), 5.8969913550106735e-05)
((np.int64(0), 'collapsed'), 1.769097406503202e-05)
((np.int64(0), 'in'), 0.019990800693486185)
((np.int64(0), 'March'), 0.00021229168878038424)
((np.int64(0), 'report'), 0.00031843753317057635)
((np.int64(0), 'suggested'), 2.3587965420042693e-05)
((np.int64(0), 'humans'), 1.769097406503202e-05)
((np.int64(0), 'illness'), 4.127893948507472e-05)
((np.int64(0), 'eating'), 4.7175930840085385e-05)
((np.int64(0), 'contaminated'), 1.1793982710021346e-05)
((np.int64(0), 'beef'), 5.8969913550106735e-05)
((np.int64(0), 'imported'), 2.9484956775053368e-05)
((np.int64(0), '47,600'), 1.1793982710021346e-05)
((np.int64(0), 'year'), 0.0017278184670181274)
((np.int64(0), 'nearly'), 0.00015921876658528817)
((np.int64(0), 'half'), 0.0004953472738208966)
((np.int64(0), 'total'), 0.0002240856714904056)
((np.int64(0), 'imports'), 7.666088761513875e-05)
((np.int64(0), 'It'), 0.0012206772104872093)
((np.int64(0), 'brought'), 0.00018280673200533087)
((np.int64(0), '4,275'), 1.1793982710021346e-05)
((np.int64(0), 'tonnes'), 0.0004835532911108752)
((np.int64(0), 'mutton'), 1.769097406503202e-05)
((np.int64(0), 'some'), 0.0009258276427366758)
((np.int64(0), '10'), 0.0011617072969371026)
((np.int64(0), 'percent'), 0.0017867883805682341)
((np.int64(0), 'overall'), 0.00011793982710021347)
((np.int64(0), 'Rare'), 5.896991355010673e-06)
((np.int64(1), 'Hendrix'), 0.0006060606060606061)
((np.int64(0), 'song'), 1.1793982710021346e-05)
((np.int64(0), 'draft'), 6.48669049051174e-05)
((np.int64(0), 'sells'), 2.3587965420042693e-05)
((np.int64(0), 'almost'), 8.255787897014943e-05)
((np.int64(0), '$'), 0.002134710870513864)
((np.int64(0), '17,000'), 1.1793982710021346e-05)
((np.int64(5), 'LONDON'), 0.013025210084033614)
((np.int64(0), 'A'), 0.0011676042882921133)
((np.int64(0), 'rare'), 4.7175930840085385e-05)
((np.int64(0), 'handwritten'), 5.896991355010673e-06)
((np.int64(5), 'U.S.'), 0.04327731092436975)
((np.int64(0), 'guitar'), 1.1793982710021346e-05)
((np.int64(0), 'legend'), 5.896991355010673e-06)
((np.int64(1), 'Jimi'), 0.00015151515151515152)
((np.int64(2), 'Hendrix'), 0.00022084805653710247)
((np.int64(0), 'sold'), 0.00016511575794029887)
((np.int64(0), 'auction'), 8.255787897014943e-05)
((np.int64(0), 'late'), 0.0003125405418155657)
((np.int64(0), 'musician'), 5.896991355010673e-06)
((np.int64(0), 'favourite'), 1.769097406503202e-05)
((np.int64(0), 'possessions'), 5.896991355010673e-06)
((np.int64(5), 'Florida'), 0.0011204481792717086)
((np.int64(0), 'restaurant'), 4.127893948507472e-05)
((np.int64(0), 'paid'), 0.00010614584439019212)
((np.int64(0), '10,925'), 5.896991355010673e-06)
((np.int64(0), 'pounds'), 0.0001356308011652455)
((np.int64(0), '16,935'), 5.896991355010673e-06)
((np.int64(7), 'Ai'), 0.00029086678301337986)
((np.int64(8), "n't"), 0.0008658008658008658)
((np.int64(8), 'no'), 0.0008658008658008658)
((np.int64(8), 'telling'), 0.0008658008658008658)
((np.int64(0), 'penned'), 5.896991355010673e-06)
((np.int64(0), 'piece'), 2.9484956775053368e-05)
((np.int64(5), 'London'), 0.008543417366946778)
((np.int64(0), 'hotel'), 5.8969913550106735e-05)
((np.int64(0), 'stationery'), 1.1793982710021346e-05)
((np.int64(0), '1966'), 1.769097406503202e-05)
((np.int64(0), 'At'), 0.0004953472738208966)
((np.int64(0), 'end'), 0.0004363773602707898)
((np.int64(0), 'January'), 0.00011793982710021347)
((np.int64(0), '1967'), 2.3587965420042693e-05)
((np.int64(0), 'concert'), 1.769097406503202e-05)
((np.int64(7), 'English'), 0.012216404886561954)
((np.int64(0), 'city'), 0.00032433452452558704)
((np.int64(5), 'Nottingham'), 0.0004201680672268908)
((np.int64(0), 'he'), 0.003432048968616212)
((np.int64(0), 'threw'), 5.8969913550106735e-05)
((np.int64(0), 'sheet'), 2.9484956775053368e-05)
((np.int64(0), 'paper'), 0.00014152779252025617)
((np.int64(0), 'into'), 0.0009435186168017078)
((np.int64(0), 'audience'), 2.9484956775053368e-05)
((np.int64(0), 'where'), 0.0005896991355010674)
((np.int64(0), 'retrieved'), 5.896991355010673e-06)
((np.int64(0), 'fan'), 1.769097406503202e-05)
((np.int64(0), 'Buyers'), 1.1793982710021346e-05)
((np.int64(0), 'also'), 0.0012619561499722842)
((np.int64(0), 'snapped'), 8.255787897014943e-05)
((np.int64(0), 'up'), 0.0018516552854733516)
((np.int64(0), '16'), 0.00032433452452558704)
((np.int64(0), 'items'), 4.127893948507472e-05)
((np.int64(0), 'were'), 0.003131302409510668)
((np.int64(0), 'put'), 0.0003420254985906191)
((np.int64(0), 'former'), 0.0006427720576961634)
((np.int64(0), 'girlfriend'), 1.769097406503202e-05)
((np.int64(1), 'Kathy'), 0.00030303030303030303)
((np.int64(2), 'Etchingham'), 0.00022084805653710247)
((np.int64(0), 'who'), 0.0025887792048496856)
((np.int64(0), 'lived'), 4.7175930840085385e-05)
((np.int64(0), 'him'), 0.0006545660404061848)
((np.int64(0), '1969'), 1.1793982710021346e-05)
((np.int64(0), 'They'), 0.0005071412565309179)
((np.int64(0), 'included'), 0.00011793982710021347)
((np.int64(0), 'black'), 0.00012383681845522414)
((np.int64(0), 'lacquer'), 5.896991355010673e-06)
((np.int64(0), 'mother'), 6.48669049051174e-05)
((np.int64(0), 'pearl'), 5.896991355010673e-06)
((np.int64(0), 'inlaid'), 5.896991355010673e-06)
((np.int64(0), 'box'), 3.538194813006404e-05)
((np.int64(0), 'used'), 0.00018280673200533087)
((np.int64(0), 'store'), 4.127893948507472e-05)
((np.int64(0), 'drugs'), 0.00012383681845522414)
((np.int64(0), 'anonymous'), 1.769097406503202e-05)
((np.int64(7), 'Australian'), 0.014834205933682374)
((np.int64(0), 'purchaser'), 5.896991355010673e-06)
((np.int64(0), 'bought'), 0.0001120428357452028)
((np.int64(0), '5,060'), 5.896991355010673e-06)
((np.int64(0), '7,845'), 5.896991355010673e-06)
((np.int64(0), 'guitarist'), 5.896991355010673e-06)
((np.int64(0), 'died'), 0.0002181886801353949)
((np.int64(0), 'overdose'), 5.896991355010673e-06)
((np.int64(0), '1970'), 1.1793982710021346e-05)
((np.int64(0), 'aged'), 4.7175930840085385e-05)
((np.int64(0), '27'), 0.0002181886801353949)
((np.int64(5), 'China'), 0.012745098039215686)
((np.int64(0), 'says'), 0.00038920142943070447)
((np.int64(5), 'Taiwan'), 0.00392156862745098)
((np.int64(0), 'spoils'), 5.896991355010673e-06)
((np.int64(0), 'atmosphere'), 3.538194813006404e-05)
((np.int64(0), 'talks'), 0.0004894502824658859)
((np.int64(5), 'BEIJING'), 0.0012605042016806723)
((np.int64(5), 'Taipei'), 0.0007002801120448179)
((np.int64(0), 'spoiling'), 1.1793982710021346e-05)
((np.int64(0), 'resumption'), 1.1793982710021346e-05)
((np.int64(6), 'Strait'), 0.001728608470181504)
((np.int64(0), 'visit'), 0.0004009954121407258)
((np.int64(5), 'Ukraine'), 0.005322128851540616)
((np.int64(7), 'Taiwanese'), 0.0008726003490401396)
((np.int64(0), 'Vice'), 1.769097406503202e-05)
((np.int64(0), 'President'), 0.0006427720576961634)
((np.int64(1), 'Lien'), 0.00030303030303030303)
((np.int64(2), 'Chan'), 0.00022084805653710247)
((np.int64(0), 'this'), 0.0016747455448230314)
((np.int64(0), 'week'), 0.000866857729186569)
((np.int64(0), 'infuriated'), 1.769097406503202e-05)
((np.int64(5), 'Beijing'), 0.0021008403361344537)
((np.int64(0), 'Speaking'), 1.1793982710021346e-05)
((np.int64(0), 'hours'), 0.0002653646109754803)
((np.int64(7), 'Chinese'), 0.007271669575334497)
((np.int64(0), 'state'), 0.0007489179020863556)
((np.int64(0), 'media'), 9.435186168017077e-05)
((np.int64(0), 'time'), 0.000849166755121537)
((np.int64(0), 'right'), 0.00021229168878038424)
((np.int64(0), 'engage'), 1.1793982710021346e-05)
((np.int64(0), 'political'), 0.00041868638620575784)
((np.int64(3), 'Foreign'), 0.0015820281601012498)
((np.int64(4), 'Ministry'), 0.007019438444924406)
((np.int64(1), 'Shen'), 0.00015151515151515152)
((np.int64(2), 'Guofang'), 0.00022084805653710247)
((np.int64(3), 'Reuters'), 0.012498022464799873)
((np.int64(0), ':'), 0.004051233060892332)
((np.int64(0), 'necessary'), 5.8969913550106735e-05)
((np.int64(0), 'opening'), 0.00018280673200533087)
((np.int64(0), 'disrupted'), 2.3587965420042693e-05)
((np.int64(0), 'authorities'), 0.000271261602330491)
((np.int64(0), 'State'), 8.84548703251601e-05)
((np.int64(0), 'quoted'), 0.000288952576395523)
((np.int64(0), 'top'), 0.000306643550460555)
((np.int64(0), 'negotiator'), 2.9484956775053368e-05)
((np.int64(1), 'Tang'), 0.0007575757575757576)
((np.int64(2), 'Shubei'), 0.00044169611307420494)
((np.int64(0), 'telling'), 2.9484956775053368e-05)
((np.int64(0), 'visiting'), 5.307292219509606e-05)
((np.int64(0), 'group'), 0.0007312269280213235)

## Viterbi Decoding

Viterbi function takes as arguments:
- `tokens`: the sentence to be decoded
- `tags`: the NER tags from 0 to 8 (without `<start>`)
- `transition_probabilities`

In [ ]:
def viterbi(tokens, tags, transition_probabilities, emission_probs):
    
    epsilon = 1e-6 # prevent zero probabilities
    
    # stores probabilities and paths for each step
    viterbi_path = []
    backpointers = []
    
    # first token initialization (root node)
    first_token = tokens[0]
    first_viterbi = {}
    first_backpointer = {}
    
    # if the first token is completely unknown (out of vocabulary)
    # true when all tags have zero emission probability for the first token (doesn't appear in training data)
    is_oov = all(emission_probs.get((t, first_token), 0) == 0 for t in tags)
    
    for tag in tags:
        transition_prob = transition_probabilities.get(("<START>", tag), epsilon)
        emission_prob = epsilon if is_oov else emission_probs.get((tag, first_token), epsilon)
        
        # multiply transition and emission probabilities for the first token (log space to prevent underflow)
        first_viterbi[tag] = math.log(transition_prob) + math.log(emission_prob)
        first_backpointer[tag] = "<START>"
    
        # first_viterbi[tag] = trans_prob * emiss_prob
        # first_backpointer[tag] = "<START>"
        
    # root node probabilities
    viterbi_path.append(first_viterbi)
    backpointers.append(first_backpointer)
    
    # forward pass for the whole sequence of tokens
    for t in range(1, len(tokens)):
        token = tokens[t]
        current_viterbi = {}
        current_backpointer = {}
        
        is_oov = all(emission_probs.get((tag, token), 0) == 0 for tag in tags)
        
        # for each token, go through all tags and calculate best score and backpointer
        for current_tag in tags:
            
            best_score = -float('inf') # minimum score
            best_prev_tag = None
            
            # save emission probability for current tag
            emission_prob = epsilon if is_oov else emission_probs.get((current_tag, token), epsilon)
            emission_score = math.log(emission_prob)
            
            # for each possible previous current token, go through all previous tags
            # and calculate the score of transitioning from every previous tag to current one 
            for prev_tag in tags:
                transition_prob = transition_probabilities.get((prev_tag, current_tag), epsilon)
                transition_score = math.log(transition_prob)
                
                # multiply transition and emission probabilities with the previous step's probability (log space)
                # use the previous tags score
                score = viterbi_path[t-1][prev_tag] + transition_score + emission_score
                
                # pick best probability/score and keep track of the best previous tag
                if score > best_score:
                    best_score = score
                    best_prev_tag = prev_tag
          
          # for current token and tag, save the best score and backpointer      
            current_viterbi[current_tag] = best_score
            current_backpointer[current_tag] = best_prev_tag
          
        # for each token after going through all tags and calculating scores, save the best scores and backpointers  
        viterbi_path.append(current_viterbi)
        backpointers.append(current_backpointer)
        
    # forward pass done
        
    # backtracking for best sequence
    best_last_tag = max(viterbi_path[-1], key=viterbi_path[-1].get) # last dictionary, get tag with highest score (key value)
    best_sequence = [best_last_tag]
    
    # get best sequence by following backpointers, start from the end of the sequence
    for t in range(len(tokens) - 1, 0, -1):
        best_prev_tag = backpointers[t][best_last_tag]
        best_sequence.insert(0, best_prev_tag) # insert at the start of the list
        best_last_tag = best_prev_tag
        
    return best_sequence

## Evaluation

In [10]:
true_labels = []
predicted_labels = []

tags = [0, 1, 2, 3, 4, 5, 6, 7, 8]
tag_names = ['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']

for _, row in df_test.iterrows():
    tokens = row['tokens']
    true_tags = row['ner_tags']
    
    # get predictions for the current sentence
    pred_tags = viterbi(tokens, tags, transition_probs, emission_probs)
    
    # store the actual and predicted tags
    true_labels.extend(true_tags)
    predicted_labels.extend(pred_tags)

# Generate the evaluation report
report = classification_report(true_labels, predicted_labels, target_names=tag_names, zero_division=0)
print(report)

              precision    recall  f1-score   support

           O       0.94      0.99      0.97     38323
       B-PER       0.93      0.48      0.63      1617
       I-PER       0.97      0.58      0.72      1156
       B-ORG       0.83      0.61      0.70      1661
       I-ORG       0.85      0.61      0.71       835
       B-LOC       0.85      0.81      0.83      1668
       I-LOC       0.78      0.66      0.72       257
      B-MISC       0.82      0.73      0.77       702
      I-MISC       0.71      0.64      0.68       216

    accuracy                           0.93     46435
   macro avg       0.85      0.68      0.75     46435
weighted avg       0.93      0.93      0.92     46435